name = "BlanketCon 23"
author = "LemmaEOF, UltraStorm"
version = "2023.8.25.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acf725505c6aac1fa54e4b669a46aea6fbb528aa74063d64b7feecbab97717c3"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"

[options]
acceptable-game-versions = ["1.20", "1.19.4"]
